### PR TITLE
Create README.md for Flutter Resources

### PR DESCRIPTION
**Pull request by pratikbutani**

### CODE REVIEW

**Comment by rahul-n18** [comment]
@pratikbutani Your PR is awesome loved the content, If you have same type of content for other framework I would be very happy to Merge your PR.

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by rahul-n18** [comment]
ill we adding hactoberfest label to this, hoping for your positive response

**Comment by rahul-n18** [comment]
Sorry we are not getting any response from you,

Thank you for contributing to this Repo

**Comment by pratikbutani** [comment]
> Sorry we are not getting any response from you,
> 
> Thank you for contributing to this Repo

I am not so much active as you are. I will definitely add new content or idea in this repo.

**Comment by rahul-n18** [comment]
Sure, Happy to hear that :)

**Comment by pratikbutani** [comment]
> Sure, Happy to hear that :)

Thank you, hope you will add `hacktoberfest` tag

**Comment by rahul-n18** [comment]
Make sure to star this Repo and contribute in future

Happy Hacking

**Comment by pratikbutani** [comment]
Yup, Already starred. Will contribute in future too.

**Pull request merged**
