### PR TITLE
Footer corrected

### PR DESCRIPTION
**Pull request by InquisitiveMe15**
Screenshot of the same.

image

### CODE REVIEW

**Comment by InquisitiveMe15** [comment]
Kindly merge it.

Thank you :)

**Comment by InquisitiveMe15** [comment]
Issue #21

**Comment by rahul-n18** [comment]
> before that Please read ReadMe File, you need to understand it's mainly not about editing a HTML page.

>We are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.
Please upload resources if you have

Please update your repo with This.

Thank You.

**Comment by InquisitiveMe15** [comment]
> > before that Please read ReadMe File, you need to understand it's mainly not about editing a HTML page.
> 
> > We are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.
> > Please upload resources if you have
> 
> Please update your repo with This.
> 
> Thank You.

Sorry! but I didn't get your point.
Are you asking me to elaborate the points mentioned by you in the pull request description?

**Comment by InquisitiveMe15** [comment]
Thank you!
Could you label this PR as **hactoberfest-accepted**
This is still showing not accepted in my profile section.

**Comment by rahul-n18** [comment]
sure :)

**Comment by rahul-n18** [comment]
There You Go...

**Comment by InquisitiveMe15** [comment]
thanks

**Pull request merged**
