### PR TITLE
fix: Navbar active page color

### PR DESCRIPTION
**Pull request by yunsuklee**
#18 

Noticed that when navigating thorugh the different pages in navbar Home was always selected while current page did not get a color update at navbar, although the page did load.

Bug was due to class "active" being forcedly set on homepage at the html of every page.

Besides, I added a script at main.js that once any page has loaded, gets the current url and updates the corresponding .nav-item's class adding .active so that its color can get updated. 

I'd appreciate if it counted for hacktoberfest!

After fix:
Screenshot from 2022-10-04 12-18-36
ontent.com/92840840/1
Screenshot from 2022-10-04 12-20-11
93795482-deb1946c-8eeb-4cb2-a697-4deafb296726.png)

### CODE REVIEW

**Comment by rahul-n18** [comment]
Yes Ill Merge your PR with Hactoberfest.
but I Have a doubt, if you can help me with it.

I usually don't Host Site's on Github, My Index.html file is Present in  sub folder called Code. how do I Fetch my index.html fine to Github Pages. 
Screenshot (51)
Screenshot (50)

**Comment by yunsuklee** [comment]
Thanks!!

I actually do not have experience hosting repos at github. If I looked what you wanna do correctly changing your site's url to the following might work:
https://[username].github.io/code/index.html

**Comment by rahul-n18** [comment]
Could you look up to it and get back to me

**Comment by yunsuklee** [comment]
Sure, would you explain me more detailed what you wanna do?

**Comment by rahul-n18** [comment]
@yunsuklee My main Idea would be to create a platform which provides Everything a Student would need in One place.
But to build this from Scratch for me It is Not possible.
So with the help of Open source I'm Collecting Info and Ideas How we can Make this Possible.

**Comment by yunsuklee** [comment]
Loving it man, I'll be looking forward to how this project develops and I'll try yo keep up contributing to it!!

**Comment by rahul-n18** [comment]
Sure Would Love It.
Join Discord so we can have Our Ideas presented

**Pull request merged**
