### PR TITLE
Student-Library new UI

### PR DESCRIPTION
**Pull request by Morbius00**
Hacktober Badge

##  Student-Library new UI

Hey @rahul-n18 the above changes you mentioned are all done few things need to added (some repo liks for project ideas,your website link and you social media links for connctions) that all.
Hope you like the new UI .
and dont forget to merge and add the hacktober label.😄

## Here all the changes you asked for :
Screenshot 2022-10-06 140142
Screenshot 2022-10-06 140237
Screenshot 2022-10-06 140316
Screenshot 2022-10-06 140406
Screenshot 2022-10-06 140516
Screenshot 2022-10-06 140653
Screenshot 2022-10-06 140846
thanks 😄

### CODE REVIEW

**Comment by Morbius00** [comment]
> Can you please add Screenshot so Ill merge this Asap
ok I am adding the ss in the comment section

**Comment by rahul-n18** [comment]
> > Can you please add Screenshot so Ill merge this Asap
> ok I am adding the ss in the comment section
> 
> 

I think there is some miscommunication

I told you to send me screenshot shot so i can see the difference before and after

**Comment by Morbius00** [comment]
> > > Can you please add Screenshot so Ill merge this Asap
> > > ok I am adding the ss in the comment section
> 
> I think there is some miscommunication
> 
> I told you to send me screenshot shot so i can see the difference before and after

where I will send you the screen shots

**Comment by rahul-n18** [comment]
in the issue sction

**Comment by Morbius00** [comment]
well i upload all the screen shots here you can check it from here .

**Comment by rahul-n18** [comment]
I have added the label and Ill be merging

Make sure to star this repo so others can see this,

Thank you
Happy Hacking

**Comment by Morbius00** [comment]
Hey @rahul-n18  your project has been excluded from hactober fest...😞

**Comment by rahul-n18** [comment]
Ill check with admin and get back to you

**Pull request merged**
