### PR TITLE
Fix style of header in responsive  issue#32

### PR DESCRIPTION
**Pull request by vardhan0604**
Fix style of header in responsiveness

PS-add hacktoberfest to this PR

after:-
image

before:-
image

### CODE REVIEW

**Comment by vardhan0604** [comment]
@rahul-n18 can you tell me what was the problem with the pr .... just curious

**Comment by rahul-n18** [comment]
hello @vardhan0604 please Understand this we are not mainly focusing on website but more on Idea and Implementation of this.

before that Please read ReadMe File, you need to understand it's mainly not about editing a HTML page.

We are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.
Please upload resources if you have.

So you can create a new Issue with Idea and Resource, surely I would love to merge your request and add Hacktoberferst tag.

**Comment by vardhan0604** [comment]
Ohh okay thanks for giving the reason

**Comment by rahul-n18** [comment]
sure :)

**Pull request closed without merging**
