### PR TITLE
Added favicon.png for your website tab

### PR DESCRIPTION
**Pull request by CandidDeer**
Hi, I've created and added favicon.png to your project to show up as a little icon on your website's browser tab. I hope you like it. I'd love for you to merge it and consider my contribution for hacktoberfest. ✨ I created this favicon myself, so no issue at all with any copyright or anything like that. I hope you enjoy it!

### CODE REVIEW

**Comment by rahul-n18** [comment]
@CandidDeer Ill be very honest I need your help and Surely Ill Merge your PR.

### help: 

- I Have created a folder called Graphic Resource
- From your Profile I got to know You are a self taught designer
- soo I would want you to add resources which you followed so it will helps others to learn graphic Design
- You can also add copyright free resource files there
- If you love Open-Source and love helping people you can write down a short guide how can someone become Graphic designer

**Comment by CandidDeer** [comment]
Hi, yes, I can do this, of course. 👍🏻 May I suggest you merge this PR and I will start working on a new one for the graphic design resources?

**Comment by rahul-n18** [comment]
@CandidDeer Don't mind me saying this but this PR has a small issue, please update and Request a PR and Ill response Immediately.

**Comment by CandidDeer** [comment]
What is the issue? The PR says it has no conflicts with the base branch and can be merged?

**Comment by CandidDeer** [comment]
I would kindly ask you to merge this PR and I will open a new one with your requested graphic design resources.

**Comment by rahul-n18** [comment]
@CandidDeer I would love to merge this but the issue here is Please read ReadMe File, you need to understand it mainly not about editing a HTML page.

We are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.
Please upload resources if you have.

If you can do this Ill Assign this with Hacktoberst tag.

Happy Hacking

I hope you understand Ill be merging once the Above things are Updated

**Comment by rahul-n18** [comment]
Sorry we got no response from you we are closing this PR

**Comment by CandidDeer** [comment]
Well, too bad. I was busy yesterday and wanted to start working on this today. But okay.

**Comment by rahul-n18** [comment]
We are actually preparing for backend, 
If you can get this work done by today we will be happy to reopen this PR

**Pull request closed without merging**
